### ISSUE TITLE
Interface zu Clients definieren

### ISSUE THREAD

**Issue by csacro** [SoPra-Team-17/LibClient#5]
Realisierung über Callback (mit cppyy).
Die Funktionsweise ist Folgende: In LibClient gibt es eine Callback Klasse, die header-only ist. Diese besitzt virtual Methoden für jede Aktion, die an den Client weitergereicht werden soll. In dem Client implementiert man dann eine Klasse, die von Callback erbt und alle pure virtual Methoden implementiert.

Anmerkungen zur Implemetierung in Python (beispielhaft in [Client #54](https://github.com/SoPra-Team-17/Client/pull/54) implementiert)
 - Klassen aus der C++ Library können nicht als Funktionsparameter verwendet werden.
 - Klassen aus der C++ Library können nicht in `__init__()` erstellt werden, sondern erst nachträglich.

(Kann auch gut sein, dass die angemerketen Punkte gehen und ich das nur nicht hinbekommen habe.)

**Comment by csacro** [comment]
Hier wäre mein Vorschlag [#54 in Client](https://github.com/SoPra-Team-17/Client/pull/54). Finde das ziemlich schick für sowohl Client als auch KI-Client.
Weitere Ideen/Vorschläge sind willkommen.

**Comment by Marco5de** [comment]
# Todo:
## Was alles in einem globalen objekt enthalten sein sollte
* [x] String Name
* [x] Bool isConnected
* [x] RoleEnum rolle
* [x] UUID SessionID
* [x] Scenario level
* [x] Matchconfig settings
* [x] CharacterInformation[] charSettings
* [x] UUID playerOneId, playerTwoId
* [x] String playerOneName, playerTwoName
* [x] List<UUID> offeredChar, List<GadgetEnum> offeredGadgets
* [x] List<UUID> chosenChar, List<GadgetEnum> chosenGadgets
* [x] Map<UUID, GadgetEnum> equipmentMap
* [x] UUID activeCharacter
* [x] List<BaseOperation> operations
* [x] State state
* [x] bool isGameOver
* [ ] UUID ownActiveChar
* [x] Statistics stats, UUID winner, VictoryEnum reason, bool hasReplay
* [x] UUID leftUserId
* [x] bool gamePaused, bool serverEnforced
* [ ] Map<String, Object> information(Meta)
* [x] strikeNr, strikeMax, string reason
* [x] ErrorTypeEnum reason
* [x] Replay Object: contains
    * UUID sessionId
    * Date gameStart, gameEnd
    * UUID playerOneId, UUID playerTwoId
    * String playerOneName, playerTwoName
    * Integer rounds
    * Scenario level
    * Matchconfig settings
    * CharacterDescription [] charSettings
    * MessageContainer [] messages

Es gibt ein LibClient Objekt. Dieses enthält private Model und private Network.
Konstruktor: Pointer auf Callback (python klasse halt callback als parent)
Erstellen von Model, network bekommt dann model und callback.
Erstellen der ganzen Getter für den Client

**Comment by csacro** [comment]
done in #9
